# File: simple-param.yml
parameters:
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false

pr:
  branches:  # Branch names to include or exclude for triggering a run.
    include: [ main ] # List of items to include. 
  paths:  # File paths to include or exclude for triggering a run.
    include: [ two/* ] # List of items to include. 
  drafts: false # Whether to start a run when a draft PR is created. Default: true.  (false,n,no,off,on,true,y,yes)
trigger:
- main

steps:
- script: echo ${{ parameters.yesNo }}