parameters:
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false

trigger: none
    
pr:
  branches:
    include:
    - main
  paths:
    include:
    - one/**


steps:
- script: echo ${{ parameters.yesNo }}
- script: env
