parameters:
- name: yesNo # name of the parameter; required
  type: boolean # data type of the parameter; required
  default: false

trigger: none
    
pr: none
#  branches:
#    include:
#    - main
#  paths:
#    include:
#    - one/**

resources:
  webhooks:
  - webhook: validationWebhook          
    connection: validationServiceConnection
      filters:
      - path:  commits[0].modified[0]      ### JSON path in the payload
        value: one/*   ### Expected value in the path provided

steps:
- script: echo ${{ parameters.yesNo }}
