name: pr-commenter.yaml

on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main

jobs:
  comment:
    if: github.repository == 'joakimstrandberg/pipeline'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.COMMENTER_TOKEN}}
          script: |
            for pipeline in 'one' 'two'; do
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '/azp run $pipeline'
              })
            done
