name: pr-validation-trigger

on:
  pull_request_target:
    branches:
      - main
      
jobs:
  comment:
    # Do not trigger if pull request is draft or not a fork
    if: |
      github.event.pull_request.draft == false || github.event.pull_request.head.repo.full_name != 'joakimstrandberg/pipeline'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git diff --name-only HEAD
      - id: pipelinenames
        name: Get pipeline names
        run: echo "pipelines=one, two" >> $GITHUB_OUTPUT
      - id: debug
        run: echo '${{ toJSON(github.event) }}'
      - id: azprun
        name: Trigger pipelines with comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.COMMENTER_TOKEN_2}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '/azp run ${{ steps.pipelinenames.outputs.pipelines }}'
            })
  
# github.event.pull_request.user.login
