name: pr-validation-trigger

on:
  pull_request_target:
    branches:
      - main
      
jobs:
  comment:
    if: github.event.pull_request.draft == false
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/github-script@v6
#        with:
#          github-token: ${{secrets.COMMENTER_TOKEN}}
#          script: |
#            let pipelines = ['one', 'two']
    runs-on: ubuntu-latest
    steps:
      - id: pipelinenames
        run: echo "pipelines=one, two" >> $GITHUB_OUTPUT
      - id: debug
        run: echo ${{ steps.pipelinenames.outputs.pipelines }}
      - id: azprun
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.COMMENTER_TOKEN_2}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '/azp run ${{ steps.pipelinenames.outputs.pipelines }}'
            })
