name: validation-workflow

on:
  pull_request:
    branches:
      - main
#  workflow_run:
#    workflows: [pr-validation-trigger]
#    types:
#      - completed
      
jobs:
  validation-workflow:
    #if: ${{ github.event.workflow_run.conclusion == 'success1' }}
    #strategy:
    #  matrix:
    #    pipeline: [one, two]
    #if: github.repository == 'hej/hej'
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/joakimstrandberg95/joakimstrandberg95'
        azure-pipeline-name: 'one'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
