name: validation-workflow

on:
  pull_request_target:
    branches:
      - main
#  workflow_run:
#    workflows: [pr-validation-trigger]
#    types:
#      - completed
      
jobs:
  validation-workflow:
    #if: ${{ github.event == 'bogus' }}
    strategy:
      matrix:
        pipeline: [one, two]
    #if: github.repository == 'hej/hej'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Azure Pipelines Action
      uses: azure/pipelines@v1.2
      with:
        azure-devops-project-url: 'https://dev.azure.com/joakimstrandberg95/joakimstrandberg95'
        azure-pipeline-name: ${{ matrix.pipeline }}
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
